#!/bin/bash

#
# DockerHub build hook (overrides default build command)
# @see https://docs.docker.com/docker-hub/builds/advanced/
# @see https://microbadger.com/labels
# @see https://stackoverflow.com/questions/45277186/is-it-possible-to-add-environment-variables-in-automated-builds-in-docker-hub
#

echo "Building image"

# Check if Dockerfile exists
if [ ! -f "$DOCKERFILE_PATH" ]; then
  echo "Dockerfile $DOCKERFILE_PATH does not exist"
  exit 1
fi

#
# Get arch from docker file name (architecture is 3th Dockerfile.<image>.<arch>)
#
arch="$(echo "${DOCKERFILE_PATH}" | cut -s -d '.' -f 3)"
arch=${arch:-'amd64'}

if [ -z "$DOCKER_TAG" ]; then
  DOCKER_TAG="latest"
fi

#
# Check if image insertion possible
# - In dockerfile at the top must be
#   - ARG FROM_IMAGE
#   - FROM ${FROM_IMAGE} Note: Here exactly one space !!
#
from=$(grep -E '^\s*FROM\s*\w*' "$DOCKERFILE_PATH" | cut -d' ' -f 2)
if [ "$from" != '${FROM_IMAGE}' ]; then
  # Normal build: Can't change base image
  
  # Add tag suffix for arch
  if [ -n "$arch" ] && [ "$arch" != "amd64" ] && ! [[ "$DOCKER_TAG" =~ -$arch\s*$ ]]; then
    suffix="-$arch"
  fi
  echo "Building: $DOCKER_REPO:$DOCKER_TAG$suffix"
  
  docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_SRC="https://github.com/SloCompTech/docker-baseimage/commit/$SOURCE_COMMIT" \
  --build-arg VERSION="$SOURCE_BRANCH" \
  -t $DOCKER_REPO:$DOCKER_TAG$suffix -f $DOCKERFILE_PATH .
else
  #
  # Get value of image variable
  # amd64: IMAGE=<repo>/<image>
  # other: IMAGE_<arch uppercase>=<repo>/<image>
  #
  if [ -z "$arch" ] || [ "$arch" == "amd64" ]; then
    imagevar="IMAGE"
  else
    imagevar="IMAGE_$(echo $arch | tr '[:lower:]' '[:upper:]')"
  fi
  IMAGE="${!imagevar}"
  if [ -z "$IMAGE" ]; then
    echo "Invalid image for $arch"
    exit 2
  fi

  #
  # Image reference to set settings
  # is equal to IMAGE_<tag>_<property> docker tags except . and - replaced by _
  #
  IMAGEREF="$(echo $DOCKER_TAG | tr '.-' '_')"

  #
  # Leave image tag untouched
  # IMAGE_<ref>_ORIG=true
  #
  imageorigtag="IMAGE_${IMAGEREF}_ORIG"
  IMAGEORIG="${!imageorigtag}"

  # Remove arch suffix from image tag if it exists
  if [ -z "$IMAGEORIG" ] && [[ "$DOCKER_TAG" =~ -$arch\s*$ ]]; then
    DOCKER_TAG="${DOCKER_TAG%-*}"
  fi

  # Add tag suffix for arch
  if [ -z "$IMAGEORIG" ] && [ -n "$arch" ] && [ "$arch" != "amd64" ]; then
    suffix="-$arch"
  fi

  #
  # Set different tag for source image
  # IMAGE_<ref>_SRCTAG=<tag>
  #
  imagesourcetagvar="IMAGE_${IMAGEREF}_SRCTAG"
  SOURCE_TAG=${!imagesourcetagvar:-$DOCKER_TAG}
  
  echo "Building: $IMAGE:$SOURCE_TAG --> $DOCKER_REPO:$DOCKER_TAG$suffix"
  
  docker build \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg FROM_IMAGE="$IMAGE:$SOURCE_TAG" \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VCS_SRC="https://github.com/SloCompTech/docker-baseimage/commit/$SOURCE_COMMIT" \
    --build-arg VERSION="$SOURCE_BRANCH" \
    -t $DOCKER_REPO:$DOCKER_TAG$suffix -f $DOCKERFILE_PATH .
fi
