#!/bin/bash

#
#   DockerHub build hook (overrides default build command)
#   @see https://docs.docker.com/docker-hub/builds/advanced/
#   @see https://microbadger.com/labels
#

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 3)
UPSTREAM_IMAGE_VERSION=$(cat ${DOCKERFILE_PATH} | grep -P 'FROM' | cut -d ' ' -f 2 | cut -d ':' -f 2 -s | cut -d '-' -f 1)

IMAGE_TAG=${UPSTREAM_IMAGE_VERSION:="latest"}
if [ -n "$BUILD_ARCH" ] && [ "$BUILD_ARCH" != "amd64" ]; then
  IMAGE_TAG="$IMAGE_TAG-$BUILD_ARCH"
fi

echo "Building images"

docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_SRC="https://github.com/SloCompTech/docker-baseimage/commit/$SOURCE_COMMIT" \
  --build-arg VERSION="$SOURCE_BRANCH" \
  -t $DOCKER_REPO:$IMAGE_TAG -f $DOCKERFILE_PATH .
