#!/bin/bash

#
#	DockerHub build hook (overrides default push command)
#	@see https://docs.docker.com/docker-hub/builds/advanced/
#

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 3 -s)
UPSTREAM_IMAGE_VERSION=$(cat ${DOCKERFILE_PATH} | grep -P 'FROM' | cut -d ' ' -f 2 | cut -d ':' -f 2 -s | cut -d '-' -f 1)

IMAGE_TAG=${UPSTREAM_IMAGE_VERSION:="latest"}
if [ -n "$BUILD_ARCH" ] && [ "$BUILD_ARCH" != "amd64" ]; then
  IMAGE_TAG="$IMAGE_TAG-$BUILD_ARCH"
fi

docker tag $IMAGE_NAME $DOCKER_REPO:$IMAGE_TAG
docker push $DOCKER_REPO:$IMAGE_TAG
